services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./input-logs:/app/input-logs
      - ./logs:/app/logs
      - ./ingest-tracker:/app/ingest-tracker
    environment:
      SERVICE: "api"
    command: ["bash","-c","uvicorn api:app --host 0.0.0.0 --port 8000"]

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./input-logs:/app/input-logs
      - ./logs:/app/logs
      - ./ingest-tracker:/app/ingest-tracker
    environment:
      SERVICE: "api"
    command: ["bash", "-c", "streamlit run app.py --server.port=8501 --server.address=0.0.0.0"]
    depends_on:
      - api
